export const answersArray = [
  {
    category: "MUZYKA POLSKA",
    answers: [
      "ZACZNIJ OD BACHA",
      "BYŁAŚ SERCA BICIEM",
      "KRYZYSOWA NARZECZONA",
      "FORMACJA NIEŻYWYCH SCHABUFF",
      "UCIEKAJ MOJE SERCE",
      "KWIAT JABŁONI",
      "KROPLĄ DESZCZU",
      "ZBIGNIEW WODECKI",
      "DŁUGOŚĆ DŹWIĘKU SAMOTNOŚCI",
      "STRACHY NA LACHY",
    ],
  },
  {
    category: "KINO ŚWIATOWE",
    answers: [
      "OJCIEC CHRZESTNY",
      "CZŁOWIEK Z BLIZNĄ",
      "BĘKARTY WOJNY",
      "PRZEMINĘŁO Z WIATREM",
      "HELIKOPTER W OGNIU",
      "SZKLANA PUŁAPKA",
      "CIENKA CZERWONA LINIA",
      "PODZIEMNY KRĄG",
      "PARK JURAJSKI",
      "MILCZENIE OWIEC",
    ],
  },
  {
    category: "SPORT",
    answers: [
      "KOMBINACJA NORWESKA",
      "SEBASTIAN KAWA",
      "GIMNASTYKA SPORTOWA",
      "KOLARSTWO SZOSOWE",
      "CONOR MCGREGOR",
      "PCHNIĘCIE KULĄ",
      "TOUR DE POLOGNE",
      "WIELKA KROKIEW",
      "RAJD MONTE CARLO",
      "FERNANDO ALONSO",
    ],
  },
  {
    category: "MUZYKA ŚWIATOWA",
    answers: [
      "LOUIS ARMSTRONG",
      "STAIRWAY TO HEAVEN",
      "CARELESS WHISPER",
      "MODERN TALKING",
      "DEPECHE MODE",
      "LED ZEPPELIN",
      "THE ROLLING STONES",
      "ARMIN VAN BUUREN",
      "ONE DIRECTION",
      "KYLIE MINOGUE",
    ],
  },
  {
    category: "GEOGRAFIA",
    answers: [
      "WYŻYNA ŚLĄSKA",
      "TATRZAŃSKI PARK NARODOWY",
      "ZAGŁĘBIE RUHRY",
      "MOUNT EVEREST",
      "GÓRA KOŚCIUSZKI",
      "NIZINA AMAZONKI",
      "WODOSPAD SIKLAWICA",
      "MORZE KARAIBSKIE",
      "ZATOKA BENGALSKA",
      "BIAŁA PODLASKA",
    ],
  },
  {
    category: "HISTORIA",
    answers: [
      "OKTAWIAN AUGUST",
      "BITWA POD CEDYNIĄ",
      "TRAKTAT WERSALSKI",
      "OBRADY OKRĄGŁEGO STOŁU",
      "POWSTANIE STYCZNIOWE",
      "NAPOLEON BONAPARTE",
      "ALEKSANDER MACEDOŃSKI",
      "WŁADYSŁAW JAGIEŁŁO",
      "POTOP SZWEDZKI",
      "BITWA POD WIEDNIEM",
    ],
  },
];
